import os
from PIL import Image

x = os.path.dirname(os.path.abspath(__file__))

mydict = {'stl': 'Cardinals.png',
          'cardnials': 'Cardinals.png',
          'mil': 'Brewers.png',
          'brewers': 'Brewers.png',
          'chc': 'Cubs.png',
          'cubs': 'Cubs.png',
          'pit': 'Pirates.png',
          'pirates': 'Pirates.png',
          'cin': 'Reds.png',
          'reds': 'Reds.png',
          'ari': 'DiamondBacks.png',
          'diamondbacks': 'DiamondBacks.png',
          'wsh': 'Nationals.png',
          'nationals': 'Nationals.png',
          'lad': 'Dodgers.png',
          'dodgers': 'Dodgers.png',
          'phi': 'Phillies.png',
          'phillies': 'Phillies.png',
          'atl': 'Braves.png',
          'braves': 'Braves.png',
          'nym': 'Mets.png',
          'mets': 'Mets.png',
          'mia': 'Marlins.png',
          'marlins': 'Marlins.png',
          'nyy': 'Yankees.png',
          'yankees': 'Yankees.png',
          'tb': 'Rays.png',
          'rays': 'Rays.png',
          'bos': 'Redsox.png',
          'red sox': 'Redsox.png',
          'bal': 'Orioles.png',
          'orioles': 'Orioles.png',
          'laa': 'Angels.png',
          'angels': 'Angels.png',
          'tor': 'BlueJays.png',
          'blue jays': 'BlueJays.png',
          'sd': 'Padres.png',
          'padres': 'Padres.png',
          'tex': 'Rangers.png',
          'rangers': 'Rangers.png',
          'col': 'Rockies.png',
          'rockies': 'Rockies.png',
          'sf': 'Giants.png',
          'giants': 'Giants.png',
          'hou': 'Astros.png',
          'astros': 'Astros.png',
          'oak': 'Athletics.png',
          'athletics': 'Athletics.png',
          'sea': 'Mariners.png',
          'mariners': 'Mariners.png',
          'min': 'Twins.png',
          'twins': 'Twins.png',
          'kc': 'Royals.png',
          'royals': 'Royals.png',
          'cws': 'WhiteSox.png',
          'white sox': 'WhiteSox.png',
          'cle': 'Indians.png',
          'indians': 'Indians.png',
          'det': 'Tigers.png',
          'tigers': 'Tigers.png'}


def GetMLBTeamLogoImage(teamName):
    filename = mydict[teamName]
    return Image.open(x + "/TeamLogos/MLB/" + filename)
